repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: ./shell/ruff.sh
    types: [python]
    language: system
  - id: black
    name: black
    entry: ./shell/black.sh
    types: [python]
    language: system
  - id: pytest
    name: pytest
    entry: ./shell/pytest.sh
    types: [python]
    language: system
  - id: flake8
    name: flake8
    entry: ./shell/flake8.sh
    types: [python]
    language: system
    pass_filenames: false
  # - id: mypy
  #   name: mypy
  #   entry: ./shell/mypy.sh
  #   types: [python]
  #   language: system
  #   pass_filenames: false
