repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: black
    name: black
    entry: ./shell/black.sh
    types: [python]
    language: system
  - id: pytest
    name: pytest
    entry: ./shell/pytest.sh
    types: [python]
    language: system
  # - id: flake8
  #   name: flake8
  #   entry: ./shell/flake8.sh
  #   types: [python]
  #   language: system
  #   pass_filenames: false
